// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"v9mzeg9sxc","name":"Pets","description":"","endpoint":"https://v9mzeg9sxc.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:39b28323-90e6-4bda-9bee-bea64c819559',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'app-hosting-mobilehub-70661998',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1calkimfzjzxx.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"app-mobilehub-70661998-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"petId"}],
    'aws_mobile_analytics_app_id': '9869e96178514235aa4ce31cccc47097',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '04004bda-fdb0-40c3-b8f5-b80f3547a301',
    'aws_project_name': 'app-2018-05-21-15-43-43',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'app-deployments-mobilehub-70661998',
    'aws_resource_name_prefix': 'app-mobilehub-70661998',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'app-userfiles-mobilehub-70661998',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_DMpNks13Q',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3dm19hkqrn5iu4nvjvrqf6i9as',
}

export default awsmobile;
